version: 2
updates:
- package-ecosystem: npm
  directory: "/amqplib"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: amqplib
    versions:
    - 0.7.0
- package-ecosystem: npm
  directory: "/rascal-and-amqplib-demo"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rascal
    versions:
    - 12.0.1
    - 12.0.3
    - 12.0.4
  - dependency-name: amqplib
    versions:
    - 0.6.0
    - 0.7.0
